"""Validate and render the public status projection from GitHub metadata.

GitHub retrieval is deliberately separate from issue normalization and
rendering, so unit tests can use deterministic fixtures without credentials or
network access. ``--validate`` checks the live canonical corpus without
comparing it to checked-in presentation files. The Pages publication pipeline
uses the default command to render its transient status document.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from collections.abc import Callable, Iterable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
STATUS_DOC = "docs/status.md"
GENERATED_START = "<!-- BEGIN GENERATED:backlog-delivery"
GENERATED_END = "<!-- END GENERATED:backlog-delivery -->"
GENERATED_NOTICE = "<!-- BEGIN GENERATED:backlog-delivery (generated by the GitHub Pages publication pipeline) -->"
STATUS_ICONS = {"done": "yes", "in-progress": "wip", "blocked": "blocked", "in-review": "review", "cancelled": "cancelled"}

_TICKET_NUMBER = re.compile(r"^BTN-(\d+)$")
_MILESTONE_NUMBER = re.compile(r"^BTN-M(\d+)\b")
_METADATA_BLOCK = re.compile(r"^## Battalion metadata\s*```(?:yaml|yml)?\s*(?P<body>.*?)```", re.IGNORECASE | re.MULTILINE | re.DOTALL)
_TITLE_PREFIX = re.compile(r"^BTN-\d+\s+[—-]\s+")
_PHASES = frozenset({"architecture", "design", "implementation", "research", "rollout", "testing"})
_PRIORITIES = frozenset({"P0", "P1", "P2", "P3", "unknown"})
_ROLES = frozenset({"architect", "driver", "reviewer", "unknown"})
_ACTIVE_STATUS_LABELS = {"status:in-progress": "in-progress", "status:blocked": "blocked", "status:in-review": "in-review"}


class IssueNormalizationError(ValueError):
    """A Battalion Issue fails the locked Issue Schema v1 contract."""


class GitHubStatusUnavailable(RuntimeError):
    """Canonical Issue or milestone data could not be retrieved from GitHub."""


@dataclass(frozen=True)
class Ticket:
    """Normalized Issue Schema v1 data used by deterministic rendering."""

    id: str
    title: str
    status: str
    phase: str
    priority: str
    assignee_role: str
    issue_number: int = 0
    milestone: str | None = None
    url: str = ""


@dataclass(frozen=True)
class Milestone:
    """A canonical GitHub milestone used by the public status projection."""

    number: int
    title: str
    state: str


@dataclass(frozen=True)
class ProjectStatus:
    """The canonical GitHub records required to render status."""

    tickets: tuple[Ticket, ...]
    milestones: tuple[Milestone, ...]


def fetch_github_issues(
    runner: Callable[..., subprocess.CompletedProcess[str]] = subprocess.run,
) -> list[dict[str, Any]]:
    """Retrieve raw records through the sole GitHub transport boundary."""
    command = ["gh", "issue", "list", "--state", "all", "--limit", "1000", "--json", "number,title,body,state,stateReason,labels,milestone,url"]
    completed = runner(command, check=True, capture_output=True, text=True, encoding="utf-8")
    payload = json.loads(completed.stdout)
    if not isinstance(payload, list):
        raise ValueError("GitHub issue retrieval returned a non-list JSON payload")
    return payload


def _fetch_github_collection(
    endpoint: str,
    runner: Callable[..., subprocess.CompletedProcess[str]],
) -> list[dict[str, Any]]:
    """Fetch every REST page without granting rendering code network access."""

    command = [
        "gh", "api", "--paginate", "--slurp",
        f"repos/{{owner}}/{{repo}}/{endpoint}?state=all&per_page=100",
    ]
    try:
        completed = runner(command, check=True, capture_output=True, text=True, encoding="utf-8")
        payload = json.loads(completed.stdout)
    except (OSError, subprocess.CalledProcessError, json.JSONDecodeError) as exc:
        raise GitHubStatusUnavailable(
            "Unable to retrieve canonical GitHub status data; no local status "
            "fallback is used. Check GitHub/network access and retry."
        ) from exc
    pages = payload if isinstance(payload, list) else None
    if pages is None:
        raise GitHubStatusUnavailable("GitHub status retrieval returned a non-list payload")
    records: list[dict[str, Any]] = []
    for page in pages:
        page_records = page if isinstance(page, list) else [page]
        if not all(isinstance(record, dict) for record in page_records):
            raise GitHubStatusUnavailable("GitHub status retrieval returned malformed records")
        records.extend(page_records)
    return records


def _rest_issue_record(issue: Mapping[str, object]) -> dict[str, object]:
    """Adapt REST Issue field spellings to the locked Issue normalizer."""

    state, state_reason = issue.get("state"), issue.get("state_reason")
    html_url = issue.get("html_url")
    return {
        **issue,
        "state": state.upper() if isinstance(state, str) else state,
        "stateReason": state_reason.upper() if isinstance(state_reason, str) else state_reason,
        "url": html_url if isinstance(html_url, str) else issue.get("url", ""),
    }


def fetch_github_status(
    runner: Callable[..., subprocess.CompletedProcess[str]] = subprocess.run,
) -> ProjectStatus:
    """Retrieve the complete canonical Issue and milestone projection.

    GitHub's Issue endpoint carries membership while the Milestone endpoint
    carries empty milestones and lifecycle state.  Both are required; a
    partial response is not silently substituted with checked-in data.
    """

    issues = _fetch_github_collection("issues", runner)
    milestones = _fetch_github_collection("milestones", runner)
    return ProjectStatus(
        tickets=tuple(normalize_issues(_rest_issue_record(issue) for issue in issues if "pull_request" not in issue)),
        milestones=tuple(normalize_milestones(milestones)),
    )


def _metadata(body: object, issue_number: object) -> dict[str, str] | None:
    if not isinstance(body, str):
        return None
    match = _METADATA_BLOCK.search(body)
    if match is None:
        return None
    parsed: dict[str, str] = {}
    for line in match.group("body").splitlines():
        line = line.strip()
        if not line:
            continue
        key, separator, value = line.partition(":")
        if not separator or not key.strip() or not value.strip():
            raise IssueNormalizationError(f"GitHub issue #{issue_number}: malformed Battalion metadata line {line!r}")
        parsed[key.strip()] = value.strip().strip("\"'")
    return parsed


def _label_names(issue: Mapping[str, object]) -> set[str]:
    labels = issue.get("labels", [])
    if not isinstance(labels, list):
        raise IssueNormalizationError(f"GitHub issue #{issue.get('number', '?')}: labels must be a list")
    names: set[str] = set()
    for label in labels:
        if isinstance(label, str):
            names.add(label)
        elif isinstance(label, Mapping) and isinstance(label.get("name"), str):
            names.add(label["name"])
        else:
            raise IssueNormalizationError(f"GitHub issue #{issue.get('number', '?')}: malformed label {label!r}")
    return names


def _one_label(labels: set[str], prefix: str, issue_number: object) -> str | None:
    matches = sorted(label for label in labels if label.startswith(prefix))
    if len(matches) > 1:
        raise IssueNormalizationError(f"GitHub issue #{issue_number}: multiple {prefix} labels: {matches}")
    return matches[0] if matches else None


def _validate_classifications(metadata: Mapping[str, str], labels: set[str], issue_number: object) -> None:
    expected_keys = {"schema_version", "ticket_id", "phase", "priority", "assignee_role"}
    unknown_keys, missing_keys = sorted(set(metadata) - expected_keys), sorted(expected_keys - set(metadata))
    if unknown_keys or missing_keys or metadata.get("schema_version") != "1":
        raise IssueNormalizationError(f"GitHub issue #{issue_number}: Issue Schema v1 metadata requires exactly {sorted(expected_keys)} (missing={missing_keys}, unknown={unknown_keys}, schema_version={metadata.get('schema_version')!r})")
    if _TICKET_NUMBER.fullmatch(metadata["ticket_id"]) is None:
        raise IssueNormalizationError(f"GitHub issue #{issue_number}: invalid ticket_id {metadata['ticket_id']!r}")
    if metadata["phase"] not in _PHASES:
        raise IssueNormalizationError(f"GitHub issue #{issue_number}: unsupported phase {metadata['phase']!r}")
    if metadata["priority"] not in _PRIORITIES:
        raise IssueNormalizationError(f"GitHub issue #{issue_number}: unsupported priority {metadata['priority']!r}")
    if metadata["assignee_role"] not in _ROLES:
        raise IssueNormalizationError(f"GitHub issue #{issue_number}: unsupported assignee_role {metadata['assignee_role']!r}")
    for key, prefix in (("phase", "phase:"), ("priority", "priority:"), ("assignee_role", "role:")):
        label, value = _one_label(labels, prefix, issue_number), metadata[key]
        if value == "unknown":
            if label is not None:
                raise IssueNormalizationError(f"GitHub issue #{issue_number}: {key}=unknown must not have {label!r}")
        elif label != f"{prefix}{value}":
            raise IssueNormalizationError(f"GitHub issue #{issue_number}: metadata {key}={value!r} disagrees with label {label!r}; expected {prefix + value!r}")


def _lifecycle_status(issue: Mapping[str, object], labels: set[str]) -> str:
    number, state, reason = issue.get("number", "?"), issue.get("state"), issue.get("stateReason")
    status_labels = sorted(label for label in labels if label.startswith("status:"))
    if state == "OPEN":
        if not status_labels:
            return "not-started"
        if len(status_labels) == 1 and status_labels[0] in _ACTIVE_STATUS_LABELS:
            return _ACTIVE_STATUS_LABELS[status_labels[0]]
        raise IssueNormalizationError(f"GitHub issue #{number}: unsupported open lifecycle labels {status_labels}")
    if state == "CLOSED":
        if status_labels:
            raise IssueNormalizationError(f"GitHub issue #{number}: closed issues cannot retain status labels {status_labels}")
        if reason == "COMPLETED":
            return "done"
        if reason == "NOT_PLANNED":
            return "cancelled"
        raise IssueNormalizationError(f"GitHub issue #{number}: unsupported closed lifecycle reason {reason!r}")
    raise IssueNormalizationError(f"GitHub issue #{number}: unsupported issue state {state!r}")


def _milestone_title(issue: Mapping[str, object]) -> str | None:
    """Return the optional canonical milestone title without inventing one."""

    milestone = issue.get("milestone")
    if milestone is None:
        return None
    if not isinstance(milestone, Mapping) or not isinstance(milestone.get("title"), str) or not milestone["title"].strip():
        raise IssueNormalizationError(f"GitHub issue #{issue.get('number', '?')}: malformed milestone")
    return milestone["title"].strip()


def normalize_milestones(milestones: Iterable[Mapping[str, object]]) -> list[Milestone]:
    """Validate and deterministically order canonical GitHub milestones."""

    normalized: list[Milestone] = []
    seen_numbers: set[int] = set()
    for milestone in milestones:
        number, title, state = milestone.get("number"), milestone.get("title"), milestone.get("state")
        if not isinstance(number, int) or number <= 0:
            raise IssueNormalizationError(f"GitHub milestone has invalid number {number!r}")
        if not isinstance(title, str) or not title.strip():
            raise IssueNormalizationError(f"GitHub milestone #{number}: title must be non-empty")
        if not isinstance(state, str) or state.lower() not in {"open", "closed"}:
            raise IssueNormalizationError(f"GitHub milestone #{number}: unsupported state {state!r}")
        if number in seen_numbers:
            raise IssueNormalizationError(f"GitHub milestone number {number} appears more than once")
        seen_numbers.add(number)
        normalized.append(Milestone(number=number, title=title.strip(), state=state.lower()))
    return sorted(normalized, key=_milestone_sort_key)


def normalize_issues(issues: Iterable[Mapping[str, object]]) -> list[Ticket]:
    """Validate and normalize raw GitHub Issues without network access.

    Issues without Battalion metadata are unrelated and ignored.  A malformed
    metadata block fails loudly, preventing a second interpretation of schema
    fields in the renderer.
    """
    tickets: list[Ticket] = []
    seen_ids: set[str] = set()
    for issue in issues:
        number = issue.get("number", "?")
        metadata = _metadata(issue.get("body"), number)
        if metadata is None:
            title = issue.get("title")
            if isinstance(title, str) and _TITLE_PREFIX.match(title):
                raise IssueNormalizationError(
                    f"GitHub issue #{number}: Battalion ticket title requires Issue Schema v1 metadata"
                )
            continue
        labels = _label_names(issue)
        _validate_classifications(metadata, labels, number)
        ticket_id = metadata["ticket_id"]
        if ticket_id in seen_ids:
            raise IssueNormalizationError(f"GitHub issue #{number}: duplicate Battalion ticket ID {ticket_id}")
        title = issue.get("title")
        if not isinstance(title, str) or not title.strip():
            raise IssueNormalizationError(f"GitHub issue #{number}: title must be a non-empty string")
        issue_number = issue.get("number")
        if not isinstance(issue_number, int):
            raise IssueNormalizationError(f"GitHub issue #{number}: number must be an integer")
        url = issue.get("url", "")
        if not isinstance(url, str):
            raise IssueNormalizationError(f"GitHub issue #{number}: url must be a string")
        seen_ids.add(ticket_id)
        tickets.append(Ticket(
            ticket_id, _TITLE_PREFIX.sub("", title.strip()), _lifecycle_status(issue, labels),
            metadata["phase"], metadata["priority"], metadata["assignee_role"], issue_number,
            _milestone_title(issue), url,
        ))
    return sorted(tickets, key=_sort_key)


def load_tickets(issues: Iterable[Mapping[str, object]]) -> list[Ticket]:
    """Normalize the canonical GitHub Issue data into renderable tickets."""
    return normalize_issues(issues)


def _sort_key(ticket: Ticket) -> tuple[int, str]:
    match = _TICKET_NUMBER.match(ticket.id)
    return (int(match.group(1)) if match else 10**6, ticket.id)


def _milestone_sort_key(milestone: Milestone) -> tuple[int, int, str]:
    """Use Battalion milestone numbers, never GitHub creation or object IDs."""

    match = _MILESTONE_NUMBER.match(milestone.title)
    if match is None:
        return (1, milestone.number, milestone.title.casefold())
    return (0, int(match.group(1)), milestone.title.casefold())


def _row(ticket: Ticket, symbol: str) -> str:
    escaped_title = ticket.title.replace("|", "\\|")
    ticket_link = f"[{ticket.id}]({ticket.url})" if ticket.url else ticket.id
    milestone = ticket.milestone or "Unassigned"
    return f"| {ticket_link} | {escaped_title} | {milestone} | {symbol} |"


def _milestone_rows(status: ProjectStatus) -> list[str]:
    """Render milestone progress from canonical membership and lifecycle state."""

    members: dict[str, list[Ticket]] = {milestone.title: [] for milestone in status.milestones}
    unassigned: list[Ticket] = []
    for ticket in status.tickets:
        if ticket.milestone is None:
            unassigned.append(ticket)
        elif ticket.milestone in members:
            members[ticket.milestone].append(ticket)
        else:
            raise IssueNormalizationError(
                f"{ticket.id} belongs to GitHub milestone {ticket.milestone!r}, "
                "which was absent from the canonical milestone response"
            )

    def row(title: str, state: str, tickets: Sequence[Ticket]) -> str:
        completed = sum(ticket.status == "done" for ticket in tickets)
        cancelled = sum(ticket.status == "cancelled" for ticket in tickets)
        open_issues = len(tickets) - completed - cancelled
        denominator = completed + open_issues
        percent = (completed * 100 // denominator) if denominator else 0
        return (
            f"| {title} | {state} | {len(tickets)} | {completed} | {open_issues} | "
            f"{cancelled} | {percent}% |"
        )

    rows = [
        row(milestone.title, milestone.state.capitalize(), members[milestone.title])
        for milestone in sorted(status.milestones, key=_milestone_sort_key)
    ]
    if unassigned:
        rows.append(row("Unassigned", "—", unassigned))
    return rows


def render_delivery_section(status: ProjectStatus | Sequence[Ticket]) -> str:
    """Render a deterministic milestone overview with active issues as drill-down.

    A ticket sequence is accepted as a compatibility convenience for callers
    that render issue-only fixtures.  Production rendering always receives the
    complete :class:`ProjectStatus` fetched from GitHub.
    """

    if not isinstance(status, ProjectStatus):
        tickets = tuple(status)
        milestone_titles = sorted({ticket.milestone for ticket in tickets if ticket.milestone})
        status = ProjectStatus(
            tickets,
            tuple(
                Milestone(index, title, "—")
                for index, title in enumerate(milestone_titles, start=1)
            ),
        )
    tickets = status.tickets

    lines = [
        GENERATED_NOTICE, "", "### Milestone overview", "",
        "| Milestone | State | Issues | Completed | Open | Cancelled | Progress |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: |",
        *_milestone_rows(status), "", "### Active work", "",
        "| Ticket | Title | Milestone | Status |", "| --- | --- | --- | --- |",
    ]
    active = [ticket for ticket in tickets if ticket.status in STATUS_ICONS and ticket.status not in {"done", "cancelled"}]
    if active:
        lines.extend(_row(ticket, STATUS_ICONS[ticket.status].capitalize()) for ticket in active)
    else:
        lines.append("| — | Nothing currently in flight | — | — |")
    planned = sum(ticket.status == "not-started" for ticket in tickets)
    lines.extend(["", f"Issue-level scope, dependencies, and acceptance criteria live in the canonical [GitHub Issues](https://github.com/lrburkholder/battalion/issues) ({planned} planned/not-started).", "", GENERATED_END])
    return "\n".join(lines)


def _replace_between(text: str, start: str, end: str, replacement: str) -> str:
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.DOTALL)
    if not pattern.search(text):
        raise ValueError(f"markers not found: {start!r}")
    return pattern.sub(lambda _: replacement, text, count=1)


IssueReader = Callable[[], list[dict[str, Any]]]


def sync_documents(root: Path = REPOSITORY_ROOT, check: bool = False, issue_reader: IssueReader = fetch_github_issues, status_reader: Callable[[], ProjectStatus] | None = None) -> list[str]:
    """Render the one public status document; return paths whose content changes."""
    status = status_reader() if status_reader is not None else ProjectStatus(tuple(load_tickets(issue_reader())), ())
    delivery = render_delivery_section(status)
    status_path = root / STATUS_DOC
    status_text = status_path.read_text(encoding="utf-8")
    new_status = _replace_between(status_text, GENERATED_START, GENERATED_END, delivery)
    changed = [STATUS_DOC] if status_text != new_status else []
    if not check:
        if STATUS_DOC in changed:
            status_path.write_text(new_status, encoding="utf-8", newline="\n")
    return changed


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--validate", action="store_true", help="validate the live canonical Issue corpus without rendering")
    args = parser.parse_args()
    if args.validate:
        fetch_github_status()
        print("canonical GitHub Issue corpus is valid")
        return
    stale = sync_documents(status_reader=fetch_github_status)
    if stale:
        print(f"updated: {', '.join(stale)}")
    else:
        print("status documentation is current")


if __name__ == "__main__":
    main()
